from committee import configuration

c = configuration('000111', '00000011111101010101011')
c.attach_bot(0, 0)
print(c)
print(c.bots[0])
print('executing local rearrange')
c.bots[0].local_rearrange()
c.bots[0].algo_iter()
print(c.bots[0])
c.bots[0].algo_iter()
print(c.bots[0])
c.bots[0].algo_iter()
print(c.bots[0])
c.bots[0].algo_iter()
print(c.bots[0])

print('executing swap')
c.bots[0].swap()
c.bots[0].algo_iter()
print(c.bots[0])
c.bots[0].algo_iter()
print(c.bots[0])
c.bots[0].algo_iter()
print(c.bots[0])
c.bots[0].algo_iter()
print(c.bots[0])
c.bots[0].algo_iter()
print(c.bots[0])
c.bots[0].algo_iter()
print(c.bots[0])
c.bots[0].algo_iter()
print(c.bots[0])
for i in range(0,30):
    c.bots[0].algo_iter()
    print(c.bots[0])

